import type Anthropic from '@anthropic-ai/sdk';
export const bookingConfirmationTools: Anthropic.Tool[] = [
  { name: 'prepare_booking', description: 'Prepare the latest appointment details for customer review. This does not book or save a request. Use again after ANY correction, then ask for fresh confirmation. Ask for email once; the customer can decline. Use only details supplied by the customer and server-provided service IDs.', input_schema: { type: 'object', additionalProperties: false, properties: {
    serviceId: { type: 'string', description: 'Exact service ID from the provided booking offerings. Required for direct scheduling.' },
    requestedService: { type: 'string', description: 'For collect-info requests, the customer’s own requested service if no catalog service matches.' },
    name: { type: 'string' }, phone: { type: 'string', description: 'Confirmed phone number in international format.' }, email: { type: 'string', description: 'Optional email. Omit when declined or unavailable.' }, emailAsked: { type: 'boolean', description: 'True only after asking once whether they want an email invitation.' }, customerAddress: { type: 'string', description: 'Customer-provided visit address; required for direct customer-site appointments.' }, startTime: { type: 'string', description: 'Business-local YYYY-MM-DDTHH:mm:00, with no offset. Direct scheduling only.' }, requestedTime: { type: 'string', description: 'Collect-info requests: copy the customer’s requested-time words without inventing a date.' }, newAppointment: { type: 'boolean', description: 'True only for an explicit request for another separate appointment after a previous result. Never set this for a repeated yes or an uncertain result.' },
  }, required: ['emailAsked'] } },
  { name: 'confirm_booking', description: 'Execute the CURRENT reviewed booking draft only after the complete subsequent customer message clearly agrees to all current details. Natural yes/please/sure is valid in context. A correction, question, partial agreement or condition is NOT consent: revise or clarify first. Never use an earlier yes. Repeated calls return the original result.', input_schema: { type: 'object', additionalProperties: false, properties: { draftId: { type: 'string' }, revision: { type: 'integer', minimum: 1 } }, required: ['draftId','revision'] } },
];
export const bookingAvailabilityTool: Anthropic.Tool = { name: 'check_availability', description: 'Check full-duration availability for one exact service. Ask which service first if needed.', input_schema: { type: 'object', additionalProperties: false, properties: { date: { type: 'string', description: 'YYYY-MM-DD in business timezone' }, serviceId: { type: 'string', description: 'Service ID from the server-provided booking offerings' } }, required: ['date','serviceId'] } };
export const BOOKING_CONFIRMATION_INSTRUCTIONS = `BOOKING CONFIRMATION RULES (replace any older create_booking instructions):
Act as a helpful receptionist. Offer the appropriate next step without pressure. Use only provided booking offerings. A callback is time reserved for the business to call, not an automated call. Business visits use the approved address; customer-site visits require the customer's address. Never guess a location or duration.
Gather the service, appropriate time and name/phone. Ask once for an optional email invitation; a refusal does not stop booking. Do not say a calendar invitation was delivered; a successful calendar result only requests it.
Call prepare_booking before asking permission. It returns the exact current review. After corrections, prepare a new revision and obtain a fresh yes to all the revised details. Interpret the whole reply naturally; do not keyword-match "yes" within a correction. Do not ask repeatedly after successful confirmation.
Only confirm_booking can submit the current reviewed draft. Collect-info mode saves a request for review, never a confirmed appointment. A pending or uncertain result is not a failure or success; do not start another booking to resolve it.
For SMS and website chat, review and confirm in this conversation. Do not offer a separate text, public booking link, automatic callback, cancellation, rescheduling, or reminder tool. After success, state the accurate result and offer further help naturally.`;
